# **Programación Básica**


Este apartado presenta un conjunto de construcciones básicas de programación, que son los bloques de construcción de la mayoría de los programas. Algunas de estas herramientas se utilizan prácticamente en todos los lenguajes de programación, por ejemplo, la ejecución condicional mediante sentencias $if$, y la ejecución en bucle mediante sentencias $for$ y $while$. Otras herramientas, como la programación basada en vectores, son más especializadas, pero son igual de importantes para una codificación eficiente de R. Una implicación es que el código que parece ser eficiente en otro lenguaje puede no ser eficiente en R.

# If else

A menudo es útil forzar la ejecución de alguna parte de un programa para que dependa de una condición. La función $if$ tiene la forma

```r
if (logical_expression) {
expression_1
...
}
```

Una extensión natural del comando $if$ incluye la parte $else$
```r
if (logical_expression) {
expression_1
...
} else {
expression_2
...
}
```

Cuando se evalúa una expresión $if$, si la expresion logical es TRUE se ejecuta la expresión del primer grupo y no se ejecuta la del segundo grupo. A la inversa, si la expresión lógica es FALSE, sólo se ejecuta la expresión del segundo grupo. 

## Ejemplo 1:

Supongamos que tenemos un vector $x$ con los promedios de calificaciones de alumnos. Deseamos contruir una función que nos indique si un alumno está por arriba o debajo del promedio de calificaciones. 

In [62]:
# vector de calificaciones
x <- c(8.6, 9.0, 10.0, 8.8, 9.4, 9.9, 9.2, 10.0, 9.2, 8.9)

In [8]:
# i-ésimo alumno
xi <- x[3]
# condicional
if(xi > mean(x)){
    print(paste('El alumno se encuentra por arriba del promeio.', sep=''))
}else{
    print(paste('El alumno se encuentra por debajo del promeio.', sep=''))
}

[1] "El alumno se encuentra por arriba del promeio."


## Ejemplo 2:

Ahora deseamos un código que nos muestre si un estudiante ha aprobado o no "Proceos Estocásticos".
SI la calificación de un estudiante es igual o mayor a 6, ENTONCES mostrar “Aprobado”, DE OTRO MODO, mostrar “Reprobado”.

In [9]:
# Calificaciones
x <- c(8.6, 9.0, 10.0, 5.5, 9.4, 9.9, 9.2, 10.0, 9.2, 8.9)

In [11]:
# Solución:
xi <- x[1]
if(xi >= 6){
    print('Aprobado')
}else{
    print('Repreobado')
}


[1] "Aprobado"


# Bucle for

El comando $for$ tiene la siguiente forma, donde $i$ es una variable simple y 1:10 es un vector, que establece el inicio y fin del iterador $i$.

```r
for (i in 1:10) {
    expression_1
...
}
```

Cuando se ejecuta, el comando $for$ ejecuta el grupo de expresiones dentro de las llaves { }, una vez por cada elemento del vector (1:10). Las expresiones agrupadas pueden utilizar $i$, que toma cada uno de los valores de los elementos del vector a medida que el bucle se repite.


## Ejemplo 1: 

Supongamos que deseamos calcular la suma de elementos de un vector $x$.

In [14]:
# Vector
x <- c(1, 2, 3, 4,5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
# definimos suma antes de acumular valores
suma <- 0
# for loop
for(i in 1:length(x)){
    suma <- suma + x[i]
}
print(suma)

[1] 120


## Ejemplo 2: 

Supongamos que tenemos una matriz $A$ en la cual deseamos multiplicar los elementos $i=i$ por $2$, y los elementos $i\neq j$ por $4$.

In [15]:
A <- matrix(1, ncol=4, nrow=4)
print(A)

     [,1] [,2] [,3] [,4]
[1,]    1    1    1    1
[2,]    1    1    1    1
[3,]    1    1    1    1
[4,]    1    1    1    1


In [17]:
# for loop
B <- matrix(1, ncol=4, nrow=4)
for(j in 1:ncol(B)){
    for(i in 1:nrow(B)){
        if(i == j){
            B[i, j] <- B[i, j]*2 

        }else{
            B[i, j] <- B[i, j]*4 
        }  
    }
}
print(B)

     [,1] [,2] [,3] [,4]
[1,]    2    4    4    4
[2,]    4    2    4    4
[3,]    4    4    2    4
[4,]    4    4    4    2


## Ejemplo 3:
Supongamos que deseamos un código que multiplique una matriz consigo misma $n$ veces.

In [24]:
A <- matrix(c(0, 1,
              1, 0), ncol=2, nrow=2, byrow=T)
print(A)

     [,1] [,2]
[1,]    0    1
[2,]    1    0


In [31]:
# definimos la potencia de la matriz
n <- 41
# for loop
for(i in 1:n){
    if(i == 1){
        Mn <- A
    }else{
        Mn <- Mn%*%A
    }
}
print(Mn)

     [,1] [,2]
[1,]    0    1
[2,]    1    0


## Ejemplo 4:

Generar un código para calcular una realización de 

\begin{equation}
S_n = S_{n-1} + X_i, \ \ \ \ S_0 = 0
\end{equation}

donde $P(X_i=1) = p$ , y $P(X_i=-1) = 1-p$ 

In [50]:
# definimos n pasos
n <- 100
# probabilidad de moverse a la derecha
p <- 0.5
# valores que puede tomar 
x.right = 1 # a la derecha
x.left = -1 # a la izquierda
# inicialización del vector
S_n = numeric(n+1)
# inicio del bucle
for(i in 2:length(S_n)){
    x_i <- sample(c(x.right, x.left), size=1, replace=T, prob=c(p, 1-p))
    S_n[i]  <- S_n[i-1] + x_i
 }
 # impresión del resultado
 print(S_n)

  [1]   0   1   2   3   4   3   2   3   2   3   2   1   2   1   2   3   2   3
 [19]   4   5   6   5   6   7   8   7   8   7   6   5   6   5   6   7   8   7
 [37]   6   5   4   3   4   5   4   3   2   3   4   3   4   3   2   1   0   1
 [55]   2   1   2   3   2   1   2   1   0  -1  -2  -1   0  -1   0  -1  -2  -3
 [73]  -4  -3  -4  -5  -6  -7  -6  -7  -8  -9 -10 -11 -10 -11 -10  -9 -10 -11
 [91] -12 -13 -14 -15 -16 -15 -14 -13 -14 -15 -16


## Ejemplo 5:

Considere el caso anterior pero para  $n$ pasos, y $m$ trajectorias. (Sugerencia, utilice un arreglo matricial de dimensión $n*m$)

# Bucle While

A menudo no sabemos de antemano cuántas veces tenemos que dar la vuelta a un bucle. Es decir, cada vez que damos una vuelta al bucle, comprobamos alguna condición para para ver si ya hemos terminado. En esta situación utilizamos un bucle $while$, que tiene la forma

```r
while (logical_expression) {
    expression_1
...
}
```

Cuando se ejecuta un comando $while$, se evalúa primero la expresión lógica. Si es **TRUE** se ejecuta el grupo de expresiones entre llaves { }. A continuación, el control se vuelve al inicio del comando: si la expresión lógica sigue siendo **TRUE**, las expresiones agrupadas se ejecutan de nuevo, y así sucesivamente. Evidentemente, para que el bucle se detenga finalmente, la expression lógica debe ser finalmente **FALSE**. Para conseguirlo, la expression lógica suele depender de una variable que se altera dentro de las expresiones agrupadas.

El bucle $while$ es más fundamental que el bucle $for$, ya que siempre podemos reescribir un bucle $for$ como un bucle $while$.

## Ejemplo 1:

Supongamos que queremos conocer el primer número entero positivo cuyo cuadrado es superior a 4000, podemos hacerlo:

In [52]:
# Variable initialization
n <- 0
square <- 0

# While loop
while(square <= 4000) {
    n <- n + 1
    square <- n ^ 2
}

## Ejemplo 2:

Crear un bucle $while$ para sumar dos vectores.

In [53]:
# vectores
x <- c(1, 2, 3, 4)
y <- c(0, 0, 5, 1)
# inicialización 
n <- length(x)
i <- 0
# inicialización del vector que almacenará la suma
z <- numeric(n)
# loop
while (i <= n) {
    z[i] <- x[i] + y[i]
    i <- i + 1
}
print(z)

[1] 1 2 8 5


## Ejemplo 3:
Supongamos que deseamos un código que multiplique una matriz consigo misma $n$ veces. Utilice un bucle $while$ para responder.

In [54]:
A <- matrix(c(0, 1,
              1, 0), ncol=2, nrow=2, byrow=T)
print(A)

     [,1] [,2]
[1,]    0    1
[2,]    1    0


In [55]:
# definimos la potencia de la matriz
n <- 40
i <- 0
# for loop
while(i <= n){
    i <- i + 1
    if(i == 1){
        Mn <- A
    }else{
        Mn <- Mn%*%A
    }
   
}
print(Mn)

     [,1] [,2]
[1,]    0    1
[2,]    1    0


## Ejemplo 4:

Generar un código para calcular una realización de 

\begin{equation}
S_n = S_{n-1} + X_i, \ \ \ \ S_0 = 0
\end{equation}

donde $P(X_i=1) = p$ , y $P(X_i=-1) = 1-p$. Con la condición de que acumule hasta que $S_n=60$, o bien $S_n=-60$.

In [60]:
# probabilidad de moverse a la derecha
p <- 0.5
# valores que puede tomar 
x.right = 1 # a la derecha
x.left = -1 # a la izquierda
# inicialización del vector
S_n = c()
S_n[1] <- 0
# inicialización
i <- 2
# inicio del bucle
while(abs(S_n[i-1]) < 60){
    x_i <- sample(c(x.right, x.left), size=1, replace=T, prob=c(p, 1-p))
    S_n[i]  <- S_n[i-1] + x_i
    i <- i + 1
 }
 # impresión del resultado
 print(S_n)

   [1]   0  -1   0   1   2   3   2   3   2   3   4   5   6   7   6   7   6   5
  [19]   4   5   6   5   6   5   4   5   6   5   6   7   8   9  10  11  12  13
  [37]  14  15  16  15  14  13  14  15  16  17  18  19  18  19  18  17  16  17
  [55]  18  17  16  15  16  17  18  19  20  21  20  21  22  21  20  19  18  19
  [73]  18  17  18  19  20  19  18  19  20  19  20  19  20  19  20  21  20  19
  [91]  20  21  22  23  24  23  22  21  20  21  20  19  20  21  20  19  20  19
 [109]  20  19  18  19  20  21  22  21  22  23  22  21  22  21  22  21  22  21
 [127]  22  23  24  23  22  21  22  23  22  21  20  21  22  21  20  19  20  19
 [145]  18  19  20  19  18  19  18  19  18  19  18  17  16  17  16  17  18  17
 [163]  16  15  14  13  14  13  14  15  16  15  14  15  16  17  16  15  14  15
 [181]  16  17  18  19  20  21  22  21  20  19  18  17  16  17  16  17  18  17
 [199]  16  15  16  17  16  17  18  17  16  17  16  15  16  15  16  17  18  17
 [217]  16  17  16  17  16  15  16  15  16  15  14  